FROM node:18
WORKDIR /app
COPY server/package.json server/package-lock.json ./
RUN npm ci --only=production
COPY server/ ./
RUN npm run build
COPY server/ ./

EXPOSE 3001
# Используем node напрямую вместо npm start
CMD ["node", "index.js"]