FROM node:18
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    git

WORKDIR /app
COPY server/package.json ./
COPY server/package-lock.json ./

RUN npm ci --only=production

COPY server/ ./
RUN npm run build
COPY server/ ./

EXPOSE 3001
# Используем node напрямую вместо npm start
CMD ["node", "index.js"]